package com.aholdusa.am.audittracking.entity;

public enum NextManagerConstants {
	
	//REQUEST VALUES
	UUID("UUID"), 
	MESSAGE_TYPE("MessageType"), 
	TERMINAL_ID("TerminalId"), 
	CDATE_TIME("DateTime"), 
	OPERATOR_NAME("OperatorName"),
	OPERATOR_ID("OperatorId"),
	LANE_NUMBER("LaneNumber"),
	TERMINALS("Terminals"),
	//RESPOND VALUES
	ACCESS_APPROVED("APPROVE"),
	ACCESS_DENIED("DECLINE"),  
	ACCESS_OVER_SHORT_PROCESSED("PROCESSED"),  
	RESPONSE("Response"),
	UNKNOWN(""),
	//SERVICE TYPE
	SIGN_ON("SignOn"),
	SIGN_OFF("SignOff"),
	CARRY_FORWARD("CarryForwardNotification"),
	AUDIT_NEEDED("AuditNeeded"),
	TILL_SUMMARY_SERVICE("/WebService/TerminalStatus/Summary?Terminal="),
	TERMINAL_STATUS_SERVICE_PREFIX_URL("/WebService/TerminalStatus/Details?Terminal="),
	OVERSHORT_ACTIVITY_TYPE("OverShortReport"),
	SIGNON_SCO_ACTIVITY("SignOnSCO"),
	SIGNOFF_SCO_ACTIVITY("SignOffSCO"),
	TERMINAL_SCO("Self Checkout"),
	TERMINAL_KIOSK("Kiosk"),
	TERMINAL_VIRTUAL("Virtual"),
	TERMINAL_FUEL("Inside Fuel"),
	OVERSHORT_ACTIVITY_RECEIVED("OverShortReportReceived"),
	TOLT_USER("TotlService"),
	TERMINAL_STATUS("TerminalStatus"),
	NUMBER_OF_TRANS("NumTrans"),
	TRANS_NUMBER("TransNum"),
	//MANAGER OPERATOR NUMBER
	MANAGER_OPERATOR_NUMBER("3300"),
	LOG_TILL_CONTENTS("TillContents"),
	OVERRIDE("Override"),
	TILL_CONTENTS("TillContents"),
	RULES_PATH("src/main/resources/com/aholdusa/am/audittracking/util/"),
	LANE_TYPE_RULES("LaneType.drl"),
	NEXT_MANAGER_RULES("NextManager.drl"),
	OVERSHORTREPORT_DELETION_RULES("OverShortAmountThreshold.drl"),
	UNASSIGNED_LANE("Unassigned"),
	SIGN_ON_APPROVED("SignOnApproved"),
	SIGN_ON_DECLINED("SignOnDeclined"),
	FUEL_LANE_AUDIT_REQUIRED("FuelLaneAuditRequired"),
	DECLINE_CURRENT("DECLINE_CURRENT"),
	DECLINE_PREVIOUS("DECLINE_PREVIOUS"),
	DECLINE_RESPONSE("Improper SignOn"),
	LANE_AUDITED("LaneAudited"),
	LANE_POSITIONED_AFTER("LanePositionedAfter"),
	LANE_POSITIONED_DURING("LanePositionedDuring"),
	NEXT_MANAGER_PORT("7200"),
	CREATED_BY("ADMIN"),
	LANE_TRANSACTIONAL_ERROR("LANE_TRANSACTIONAL_ERROR"),
	EMPLOYEE_TRANSACTIONAL_ERROR("EMPLOYEE_TRANSACTIONAL_ERROR"),
	EMPLOYEE_NONTRANSACTIONAL_ERROR("EMPLOYEE_NONTRANSACTIONAL_ERROR"),
	AUDIT_TRANSACTIONAL_ERROR("AUDIT_TRANSACTIONAL_ERROR"),
	LANE_HISTORY_TRANSACTIONAL_ERROR("LANE_HISTORY_TRANSACTIONAL_ERROR"),
	INVALID_NETWORK_NAME_ERROR("INVALID_NETWORK_NAME_ERROR"),
	NOT_RESOLVABLE_POS_URL_ERROR("NOT_RESOLVABLE_POS_URL_ERROR"),
	INVALID_SIGNOFF_REQUEST_WITHOUT_SIGNON_ERROR("SIGNOFF_REQUESTED_WITHOUT_CORRESPONDING_ SIGNON"),
	INVALID_SIGNOFF_REQUEST_POS_ERROR("INVALID SIGNOFF REQUEST : POS SYSTEM"),
	SQLEXCEPTION_OCURRED_ERROR("SQLEXCEPTION_OCURRED"),
	RUN_TIME_EXCEPTION("ERROR"),
	DEFAULT_NETWORK("0.0.0.0");

	
	
 
	private String value;
 
	private NextManagerConstants(String value) {
		this.value = value;
	}
 
	public String getValue() {
		return value;
	}

}

 